### ISSUE TITLE
R-107 Añadir medición de los indicadores de objetivos 4, 5 y 6 del trienal 2021 [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#107]

**Comment by vtamara** [comment]
Implementado.

**Comment by vtamara** [comment]
![Crecer CINEP-PPP 1-0-b5 15-8-2021 3-45-45 a- m-](https://user-images.githubusercontent.com/701221/129472638-2e56520d-1b2c-426c-8e94-686195e64381.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-08-20 13-30-16](https://user-images.githubusercontent.com/10052756/130278015-ad3a0c27-33f4-4d0c-bf52-a956ee320fc1.png)
