### ISSUE TITLE
F-109 En sitio de producción responsables de línea no podía ver actividades de marco lógico de proyecto de Tipos comunes, ni calidad.

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#109]

**Comment by vtamara** [comment]
Resuelto.

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-25 14-55-28](https://user-images.githubusercontent.com/10052756/126911755-590980ce-6642-4dc3-a367-bccb2e1c07f6.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-25 17-02-17](https://user-images.githubusercontent.com/10052756/126914812-5afe7e9d-2aea-480b-988e-56fe90160114.png)  con  pruebald no se ve Tipos de actividades comunes

![image](https://user-images.githubusercontent.com/10052756/126914570-3c0d4199-b998-4cd2-9ffc-47e9ec7f5696.png) con cor1440 si se ve
