### ISSUE TITLE
R-116 Ajustar indicadores de publicación en revistas y libros a todas las líneas

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#116]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-25 17-36-42](https://user-images.githubusercontent.com/10052756/126915549-4e59a5a5-7fbb-4677-ab01-f62b2445f594.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-08-20 14-14-18](https://user-images.githubusercontent.com/10052756/130282800-e7274a60-8b25-4bb7-81f3-10b00807643c.png)
