### ISSUE TITLE
R-117 Agregar ISBN a publicación (Edwin)

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#117]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-25 17-56-09](https://user-images.githubusercontent.com/10052756/126915967-086e4092-4a2d-4327-80d8-711838b3ceb3.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-25 17-57-53](https://user-images.githubusercontent.com/10052756/126916013-646afcc9-9bdb-424e-9535-2a82b1bd0ae5.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-25 17-56-09](https://user-images.githubusercontent.com/10052756/126916039-fc3e389a-2dd9-437e-97b5-55638ba070ab.png)
