### ISSUE TITLE
F-26 En sitio de producción desde listado de organización social no genera listado STCIV con contactos

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#26]

**Comment by vtamara** [comment]
Solucionado.

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-23 18-20-14](https://user-images.githubusercontent.com/10052756/123179856-d79fa180-d44f-11eb-8eaa-812119758817.png)
![Captura de pantalla de 2021-06-23 18-20-25](https://user-images.githubusercontent.com/10052756/123179875-dec6af80-d44f-11eb-89d8-e541252add66.png)
