### ISSUE TITLE
F-28 en sitio de desarrollo no permite editar tabla básica comunicados

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#28]

**Comment by vtamara** [comment]
Resuelto

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-23 18-16-42](https://user-images.githubusercontent.com/10052756/123179565-4cbea700-d44f-11eb-882c-1a5b6d8cf044.png)
