### ISSUE TITLE
R-30 En formularo actividad debajo de la fila de población por etnia añadir otra por Rango de edad inicialmente con las opciones Jóvenes y Otros.  Dinámicamente Otros debe cambiar cuando se cambia suma por sexo o cuando se cambia Jovenes para que el total por rango de edad coincida con el total por sexo. [1,2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#30]

**Comment by vtamara** [comment]
Implementado.
![Crecer CINEP-PPP 1-0-b5 14-5-2021 9-56-33 p- m-](https://user-images.githubusercontent.com/701221/118346186-44458900-b4ff-11eb-8ab9-285a7da0d9de.png)

**Comment by BlancaInesAcosta** [comment]
![Uploading Captura de pantalla de 2021-05-20 20-52-49.png…]()

**Comment by BlancaInesAcosta** [comment]
![Uploading Captura de pantalla de 2021-05-20 20-54-51.png…]()
