### ISSUE TITLE
R-34 En formulario de actividad los convenios financiados y sus  actividades de marco lógico ahora se especifican en una tabla.  Se actualiza interrelacion entre fecha, grupo, actor social, proyecto, actividad de marco lógico y subformularios que se incrustan por actividades de marco lógico que lo requieran [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#34]

**Comment by vtamara** [comment]
Implementado:
![Crecer CINEP-PPP 1-0-b5 14-5-2021 9-49-55 p- m-](https://user-images.githubusercontent.com/701221/118346051-570b8e00-b4fe-11eb-8aa0-fc28c0dae9f0.png)


Notar que:
* al cambiar la fecha de la actividad, se restringen los proyectos a los vigentes en esa fecha.
* Al cambiar el grupo (1) se restringen compromisos institucionales a los que incluyen el grupo, (2) se restringen actores sociales a los que son contacto de ese grupo.

**Comment by BlancaInesAcosta** [comment]
![Uploading Captura de pantalla de 2021-05-20 19-46-14.png…]()
