### ISSUE TITLE
R-35 Crear proyecto plan trienal 2021-2023.  Como no tiene actividades, emplear indicadores como actividades de marco lógico cuando se requieran para medir indicadores de resultado.

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#35]

**Comment by vtamara** [comment]
Implementado.  Se trata del proyecto 22.  

[screencapture-crecer-cinep-org-co-22443-proyectosfinancieros-21-edita-2021-05-14-21_39_33.pdf](https://github.com/pasosdeJesus/cor1440_cinep/files/6481786/screencapture-crecer-cinep-org-co-22443-proyectosfinancieros-21-edita-2021-05-14-21_39_33.pdf)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-05-20 19-07-10](https://user-images.githubusercontent.com/10052756/119063431-b0f8d180-b99e-11eb-8e58-1ca86ff8ec9c.png)
