### ISSUE TITLE
R-36 Crear proyecto con tipos de actividad de marco lógico.  Poner en este los tipos de actividad del trienal anterior con los cambios del nuevo.  Homologar información existente para que en lugar de la tabla básica tipos de actividad se use este proyecto.

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#36]

**Comment by vtamara** [comment]
Implementado.  Se trata del proyecto 22:
![screencapture-crecer-cinep-org-co-22443-proyectosfinancieros-22-edita-2021-05-14-21_44_22](https://user-images.githubusercontent.com/701221/118345936-95ed1400-b4fd-11eb-858e-4170763f7812.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-05-20 19-34-39](https://user-images.githubusercontent.com/10052756/119065186-9aed1000-b9a2-11eb-947d-e773f62e4f36.png)
