### ISSUE TITLE
R-32 Al editar compromiso institucional existente con grupos deshabiltitados, en pestaña recursos humanos, que entre los grupos se incluyan los grupos deshabilitados, pero que permita añadir sólo grupos habilitados [0,4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#37]

**Comment by vtamara** [comment]
Implementado. 
![Crecer CINEP-PPP 1-0-b5 14-5-2021 9-29-29 p- m-](https://user-images.githubusercontent.com/701221/118345637-7f45bd80-b4fb-11eb-8c0b-3aace977c5a6.png)

El pantallazo muestra un proyecto que tenía grupos del trienal anterior (no se pierden) y al final un grupo del trienal actual.

En nuevos proyectos sólo permite elegir grupos del trienal actual.

**Comment by BlancaInesAcosta** [comment]
![Uploading Captura de pantalla de 2021-05-20 18-52-45.png…]()

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-05-20 18-52-45](https://user-images.githubusercontent.com/10052756/119062907-73477900-b99d-11eb-9487-ceaf4f455f0f.png)
