### ISSUE TITLE
R-39 Que al editar una nueva actividad queden por omisión como proyectos (inicialmente sin actividades): plan trienal, tipos de actividades comunes y sistema de calidad [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#39]

**Comment by vtamara** [comment]
Implementado --aunque pueden cambiar si se cambia la fecha de la actividad o el grupo.

![Crecer CINEP-PPP 1-0-b5 14-5-2021 9-53-10 p- m-](https://user-images.githubusercontent.com/701221/118346102-d0a37c00-b4fe-11eb-97d2-937fb1c33b36.png)

**Comment by BlancaInesAcosta** [comment]
![Uploading Captura de pantalla de 2021-05-20 19-48-51.png…]()
