### ISSUE TITLE
R-41 Que al editar un compromiso institucional, en la pestaña Informes, que la tabla de productos sea adaptable y  agregar antes de detalle una columna "Indicador al que aporta".  Debe permitir elegir uno de los indicadores de objetivo o de resultado del marco lógico del mismo proyecto [4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#41]

**Comment by vtamara** [comment]
Con https://github.com/pasosdeJesus/cor1440_cinep/commit/8bd5d1806f06895e3ed32a3a925f18c706346113 agregué indicadores a la hoja de vida de un compromiso institucional.

Guarda bien la información que se ingresa:
![Crecer CINEP-PPP 1-0-b5 3-6-2021 10-25-44 a- m-](https://user-images.githubusercontent.com/701221/120670513-1ac0b300-c456-11eb-8bee-4ece4705dfc0.png)

Pero al volver a editar no presenta lo almacenado:
![Crecer CINEP-PPP 1-0-b5 3-6-2021 10-30-08 a- m-](https://user-images.githubusercontent.com/701221/120671113-af2b1580-c456-11eb-9b2a-1d16850ab1ce.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-06 16-30-08](https://user-images.githubusercontent.com/10052756/120940807-b10a0880-c6e4-11eb-8fd0-354c41e560c8.png)

**Comment by BlancaInesAcosta** [comment]
P-U-R41  Probar  R-41, R-53, R-52, R-54  [1]

**Comment by vtamara** [comment]
Arreglado.
