### ISSUE TITLE
R-43 Crear nuevos grupos de acuerdo a organigrama de nuevo plan trienal, mover usuarios a la nueva estructura, deshabilitar grupos anteriore para nuevos proyectos y actividaes (pero preservarlos en actividades y proyectos históricos).

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#43]

**Comment by vtamara** [comment]
Implementado. Pueden verse los grupos y las personas de cada uno desde Administrar->Directorio/Organigrama.

El listade de grupos puede verse desd Adminsitrar->Tablas Básicas eligiendo Grupos.  Es mejor en el filtro de habilitado dejar SI, para no ver los grupos deshabilitados del trienal anterior.

![screencapture-crecer-cinep-org-co-22443-admin-grupos-2021-05-14-21_16_04](https://user-images.githubusercontent.com/701221/118345368-a69b8b00-b4f9-11eb-8bc6-5e4f5879e317.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-05-20 18-28-22](https://user-images.githubusercontent.com/10052756/119061217-76d90100-b999-11eb-93f5-a18ac73de8e6.png)

**Comment by BlancaInesAcosta** [comment]
P-U-43  Probar  R-43, R-32, R-35, R-36, R-33, R-34, R-39, R-29, R-30, R-31  [1]
