### ISSUE TITLE
R-44 Renombrar ACTOR DE MISIÓN por ACTOR ALIADO DE MISIÓN [0,2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#44]

**Comment by vtamara** [comment]
![image](https://user-images.githubusercontent.com/701221/118743285-b081fe80-b817-11eb-8d00-05d30170dcc7.png)

**Comment by BlancaInesAcosta** [comment]
P-U-44  Probar R-44, R-46  [0.4]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-05-22 12-29-01](https://user-images.githubusercontent.com/10052756/119235812-dbab6d00-baf9-11eb-874f-86f1edf7ce07.png)
