### ISSUE TITLE
R-46 Ajustar sectores de las organizaciones sociales a las del Plan Trienal 2021-2023 [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#46]

**Comment by vtamara** [comment]
![image](https://user-images.githubusercontent.com/701221/118743447-ffc82f00-b817-11eb-8779-d40e0a91e8bb.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-05-22 12-34-03](https://user-images.githubusercontent.com/10052756/119235858-14e3dd00-bafa-11eb-830c-1a1c86b41056.png)
