### ISSUE TITLE
R-52 En formulario de organización social cambiar la caja de verificación Línea Base 2018-2020, por un cuadro de selección múltiple con opciones de tabla básica Línea Base. Homologar los de la línea base 2018-2020.  Replicar en vista resumen y en listado. Heredar permisos como estaban para la edición de la caja de verificación (i.e sólo administradores pueden modificar línea base) [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#52]

**Comment by vtamara** [comment]
En formulario:
![Crecer CINEP-PPP 1-0-b5 3-6-2021 9-41-41 a- m-](https://user-images.githubusercontent.com/701221/120663751-ea761600-c44f-11eb-9ae5-0dba35bf7a2d.png)

En listado:
![Crecer CINEP-PPP 1-0-b5 3-6-2021 9-40-50 a- m-](https://user-images.githubusercontent.com/701221/120663618-cc101a80-c44f-11eb-8c65-d5aaed78d901.png)

En resumen:
![Crecer CINEP-PPP 1-0-b5 3-6-2021 9-42-10 a- m-](https://user-images.githubusercontent.com/701221/120663807-fb268c00-c44f-11eb-93d9-abb520e8fb52.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-06 16-39-19](https://user-images.githubusercontent.com/10052756/120940983-d3505600-c6e5-11eb-8138-7910e91e9c2c.png)
