### ISSUE TITLE
R-53 Nueva tabla básica Línea Base inicialmente con opciones "PLAN TRIENAL 2018-2020" y "PLAN TRIENAL 2021-2023" editable por adminsistrador unicamente [1,6]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#53]

**Comment by vtamara** [comment]
![Crecer CINEP-PPP 1-0-b5 3-6-2021 9-27-37 a- m-](https://user-images.githubusercontent.com/701221/120661501-f5c84200-c44d-11eb-862a-533835f24685.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-06 16-33-50](https://user-images.githubusercontent.com/10052756/120940908-4f966980-c6e5-11eb-9a2d-9e2a67e5970b.png)
