### ISSUE TITLE
R-56 En tabla básica municipio agregar un campo de selección múltiple con etiquetas. Entre las etiquetas agregar "PDET 2021". Marcar los 170 municipios PDET (según del documento adjunto).

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#56]
[mapa web regiones ART.pdf](https://github.com/pasosdeJesus/cor1440_cinep/files/6615824/mapa.web.regiones.ART.pdf)

**Comment by vtamara** [comment]
Ahora tabla básica Municipio deja agregar etiqueta:
![Crecer CINEP-PPP 1-0-b5 15-6-2021 8-05-37 p- m-](https://user-images.githubusercontent.com/701221/122167734-fba42700-ce40-11eb-97f6-635a2432b0b5.png)

Listado de municipos presenta etiqueta, deja filtrar y al filtrar por PDET 2021 se ven los 170:
![screencapture-192-168-10-1-3000-admin-municipios-2021-06-15-20_07_41](https://user-images.githubusercontent.com/701221/122167803-137bab00-ce41-11eb-9008-d65283359be9.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-10 14-38-31](https://user-images.githubusercontent.com/10052756/122585282-f69dce00-d020-11eb-9ff6-2da85a9b9e4d.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-18 10-38-06](https://user-images.githubusercontent.com/10052756/122585664-5a27fb80-d021-11eb-83a9-5d42747ccede.png)

**Comment by BlancaInesAcosta** [comment]
P-U-56  Probar R-56, R-59, R-60, R-61, R-63, R-64, R-65  [1]
