### ISSUE TITLE
F-58 En tablas básicas al crear un nuevo Tipo de indicador genera error. "La ficha tiene 1 error. En 'Datointermedioti' no es válido 'Nombreinterno'"

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_cinep#58]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-15 11-28-03](https://user-images.githubusercontent.com/10052756/122095442-032ce700-cdd3-11eb-894a-56326b5ced89.png)

**Comment by vtamara** [comment]
Ya no deben crearse tipos de indicador.  Esa tabla desaparecerá proximamente.

**Comment by BlancaInesAcosta** [comment]
P-U-58  Probar  F-58, F-70, F-28, F-26, F-72, R-73  [1]
