### ISSUE TITLE
R-62 Medición del segundo indicador O1.I2

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#62]
Depende de que se haga el inventario de todas las escuelas rurales de las 3 regiones priorizadas --esperamos respuesta escrita de Marco Fidel de las 3 regiones y de las personas que sistematizarán las escuelas rurales de las mismas.

Las escuelas rurales debe sistematizarse como Organizaciones Sociales en el sector Escuela Rural que se creó con fines de este indicador:

![Crecer CINEP-PPP 1-0-b5 15-6-2021 3-32-26 p- m-](https://user-images.githubusercontent.com/701221/122119603-046c0d00-cdef-11eb-91a5-9a2a7b510a65.png)

**Comment by vtamara** [comment]
Se mide como indicador de efecto con los registros de avance que sistematicen los responsables a cargo (que definirá Marco Fidel).

![Crecer CINEP-PPP 1-0-b5 15-6-2021 4-14-22 p- m-](https://user-images.githubusercontent.com/701221/122124338-c2de6080-cdf4-11eb-84eb-9cc464a6914b.png)

Aún falta refinar la formula.

El 90% se alcanza al 6to semestre, comenzando con una meta de 15% el primer semestre e incrementos de 15% por semestre.

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-08-19 10-53-18](https://user-images.githubusercontent.com/10052756/130101685-74c08e39-867a-4208-a901-85129dbede82.png)

**Comment by BlancaInesAcosta** [comment]
P-U-62  Probar  R-62, R-66. R-107, R-82, R-116  [1]
