### ISSUE TITLE
R-66 Medición del sexto indicador O3.I2

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#66]
Los investigadores registran avance en este indicador de resultado, mediante actividades relacionadas con el `PLAN TRIENAL 2021-2023` con actividad de marco lógico `O3.R3.A3.2 Estrategia en municipio PDET para brindar garantías para protestar.`:
![Crecer CINEP-PPP 1-0-b5 17-6-2021 9-58-23 a- m-](https://user-images.githubusercontent.com/701221/122422190-92acd400-cf52-11eb-9d0e-d8c8b42cab48.png)

Es muy importante que al diligenciar una actividad para hacer avanzar esste indicador, especifique el municipio, que debería ser uno de los 170 municipios PDET de este mapa: 
![pdet-0](https://user-images.githubusercontent.com/701221/122422645-ecad9980-cf52-11eb-9168-cc0679fcf5b0.jpg)
![pdet-1](https://user-images.githubusercontent.com/701221/122422672-f1724d80-cf52-11eb-83ee-c1b321d4f632.jpg)

**Comment by vtamara** [comment]
Para marcar los municipios se agrega a la tabla básica municipio el campo etiqueta y se añade la etiqueta 'MUNICIPIO PDET 2021'
![Crecer CINEP-PPP 1-0-b5 15-6-2021 8-05-37 p- m-](https://user-images.githubusercontent.com/701221/122142435-0fd22f00-ce15-11eb-9241-209f28c6a9e4.png)

Se marcan con esta etiqueta los 170 municipios PDET.

El campo etiqueta se añade al listado de municipios, junto con un filtro, al usarse pueden verse los 170 municipios:
![screencapture-192-168-10-1-3000-admin-municipios-2021-06-15-20_07_41](https://user-images.githubusercontent.com/701221/122142560-60498c80-ce15-11eb-96c3-6d4516fea8eb.png)

**Comment by vtamara** [comment]
El formulario para los efectos de este indicador se amplia para solicitar el municipio.
![screencapture-crecer-cinep-org-co-4000-efectos-nuevo-2021-06-16-01_16_52](https://user-images.githubusercontent.com/701221/122167431-905a5500-ce40-11eb-96bc-26bab902a42d.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-08-19 10-53-18](https://user-images.githubusercontent.com/10052756/130103265-e5a51dcf-190d-4a5e-b684-8ceb0cb2acec.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-08-20 11-45-59](https://user-images.githubusercontent.com/10052756/130266746-74933a5d-1af6-47c5-8719-7a762528f3da.png)
