### ISSUE TITLE
F-70 Al editar una medición de indicador y actualizar genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440_cinep#70]

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-18 12-00-55](https://user-images.githubusercontent.com/10052756/122594821-2a7ef080-d02d-11eb-8941-55a10c9623fe.png)
![Captura de pantalla de 2021-06-18 12-01-10](https://user-images.githubusercontent.com/10052756/122594831-2f43a480-d02d-11eb-811c-0965642ceb7d.png)

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/cor1440_gen/commit/b1fbece74f4406a278e7e9941c6fa1b9fd0b06a9

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-23 18-15-12](https://user-images.githubusercontent.com/10052756/123179452-0b2dfc00-d44f-11eb-8991-20a64d5d22b5.png)
