### ISSUE TITLE
R-73 Contactos de organizaciones sociales permiten especificar Sexo

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#73]

**Comment by vtamara** [comment]
Implementado

![Crecer CINEP-PPP 1-0-b5 19-6-2021 4-51-11 p- m-](https://user-images.githubusercontent.com/701221/122656279-91c89d80-d11e-11eb-9aed-e04556411a07.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-06-23 17-35-21](https://user-images.githubusercontent.com/10052756/123177607-36165100-d44b-11eb-9061-3f3a2bf712f8.png)
