### ISSUE TITLE
R-77 Quitar de trienal actividad de marco lógico O3R3A3.1 I porque el indicador ahora se mide como si fuera de efecto

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#77]
Se quitó manualmente de sitio de producción.

**Comment by vtamara** [comment]
Eliminado con migración.

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-14 15-09-25](https://user-images.githubusercontent.com/10052756/125694189-73612a74-0bd4-4241-84a2-6a29782299c2.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-27 07-09-41](https://user-images.githubusercontent.com/10052756/127151258-fe29d01f-2288-4075-8d34-73a01adf3fce.png)
