### ISSUE TITLE
F-78 En actividad al elegir Solicitud de Anticipo no sale caja para elegir fecha --sólo después de guardar y volver a editar [0,4]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#78]

**Comment by vtamara** [comment]
Propuesta de mejora en https://github.com/pasosdeJesus/mr519_gen/pull/24

**Comment by alejocruzrcc** [comment]
Prueba realizada de usuario en caso de una actividad nueva. 

https://user-images.githubusercontent.com/12545631/125733200-a9a927ec-79eb-4112-ba26-2092e89543e8.mp4

**Comment by vtamara** [comment]
Resuelto con https://github.com/pasosdeJesus/mr519_gen/pull/24
