### ISSUE TITLE
F-80 En listado de compromisos institucionales error al filtrar por financiador

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#80]
<img width="640" alt="thumbnail_Captura de Pantalla 2021-06-25 a la(s) 6 53 50 p  m" src="https://user-images.githubusercontent.com/701221/123495559-dc985880-d5e9-11eb-8832-011a7a5942a9.png">

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-14 16-29-36](https://user-images.githubusercontent.com/10052756/125695551-a3104338-e5d4-480c-a900-00dea4df13bb.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-58-54](https://user-images.githubusercontent.com/10052756/126238083-5f076175-0995-4c5f-a705-896e7fc98f6b.png)
