### ISSUE TITLE
F-81 No funciona Exploración Visual de Datos

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#81]

**Comment by vtamara** [comment]
Vuelve a operar

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-14 16-20-39](https://user-images.githubusercontent.com/10052756/125694603-9eef7906-bb0c-4ad4-b5ad-caf73f379485.png)
Al elegir Datos --> Explorador visual de datos relacionados genera error

**Comment by vtamara** [comment]
![screencapture-crecer-cinep-org-co-4000-casos-mapatiempo-2021-07-15-09_13_20](https://user-images.githubusercontent.com/701221/125802759-929493a6-b4f0-492c-a860-18d3e4e1e71c.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-32-30](https://user-images.githubusercontent.com/10052756/126235802-9db7cf30-a661-4843-973e-4ebe1da6bd00.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-57-26](https://user-images.githubusercontent.com/10052756/126237951-5e2f0cfd-4352-4876-a6f4-e91a8cdaf953.png)
