### ISSUE TITLE
R-82 Desde resumen de la medición de indicador presentar resultado y meta de la tabla de puntos de medición con una gráfica de líneas. No usar CDNs sin sprockets o webpacker. Hacer el cambio en cor1440_gen. Emplear librería usada por Dashboardkit para gráficas [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#82]

**Comment by vtamara** [comment]
![screencapture-181-143-184-115-2300-mindicadorespf-23-2021-07-21-07_13_42](https://user-images.githubusercontent.com/701221/126487677-a2a3c62d-c18c-494d-a6a2-f00b8a8b8bf0.png)

Puede ser una gráfica de líneas con 2 series de tiemmpo:
* Una línea con fecha fin (eje x) versus resultado (eje y) de color amarillo.
* Otra línea con fecha fin (eje x) versus meta (eje y) de color verde.

Asi se ve para cada periodo que tan bien se alcanza la meta y a la vez el progreso.

**Comment by alejocruzrcc** [comment]
Pruebas:  Uso de la librería apexcharts.js y gema apexcharts para medición de indicadores resultado y meta vs fecha
![Captura de pantalla de 2021-07-22 18-52-00](https://user-images.githubusercontent.com/12545631/126722886-06508276-3260-4f98-9d83-6e4028c1dc61.png)

**Comment by vtamara** [comment]
Implementado presentado a Martha Marquez.

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-08-20 13-31-55](https://user-images.githubusercontent.com/10052756/130278199-3f5f42c1-fd29-4302-bf29-5374763662fb.png)
