### ISSUE TITLE
R-87 En actividad al elegir en Tipos Comunes la actividad "Publicación de un producto" desplegar los campos del formulario publicación y permitir diligenciarlos [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#87]

**Comment by vtamara** [comment]
Al añadir Comunicaciones: Publicación de producto:

![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-52-21 p- m-](https://user-images.githubusercontent.com/701221/125139386-0ebfb500-e0d6-11eb-8881-e4a28c940439.png)

Al eliminarlo:

![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-52-52 p- m-](https://user-images.githubusercontent.com/701221/125139442-2860fc80-e0d6-11eb-8392-a9f43e5b8010.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-14 14-32-25](https://user-images.githubusercontent.com/10052756/125682028-d969b56b-71a8-4838-a0c5-ec3e05dc696a.png)
Al añadir un formulario(publicación de un producto) al proyecto(TIPOS DE ACTIVIDADES COMUNES) y guardar, al volver a editar no ha guardado el formulario
