### ISSUE TITLE
R-91 Ajustar indicadores y metas del plan trienal [2]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#91]

**Comment by vtamara** [comment]
- []  El indicador O1.I2 debe ser "El 90% de las sedes de escuelas rurales acompañadas adoptan planes de transformación educativa, construyen una agenda educativa de acuerdo a sus necesidades étnicas y culturales en 2 municipios."
- [] El indicador O3.I2 debe ser "En el 10% de los municipios PDET se han implementado estrategias que cualifican el debate público (posiciona nuevas narrativas) y escenarios de diálogo y concertación multiactor (activistas, autoridades civiles y policía nacional) encaminados a brindar mayores garantías para ejercer el derecho a protestar y la implementación adecuada del acuerdo de paz." 
- [] En proyecto de Tipos de actividades comunes cambiar actividad Comunicaciones: Publicaciones por Comunicaciones: Publicación de un producto 
- [] Ajustar las metas de los 6 primeros indicadores para cada uno de los 6 semestres del trienio.
- [] Añadir un indicador para el objetivo OG3 "Nueve (9) revistas Cien Dias, que analizan la coyontura nacional y regional del país."

**Comment by vtamara** [comment]
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-36-00 p- m-](https://user-images.githubusercontent.com/701221/125138160-c3a4a280-e0d3-11eb-90cf-bfa08ca54583.png)

![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-36-20 p- m-](https://user-images.githubusercontent.com/701221/125138193-cef7ce00-e0d3-11eb-88a5-66d67d94717f.png)

![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-37-22 p- m-](https://user-images.githubusercontent.com/701221/125138265-f51d6e00-e0d3-11eb-83ff-c3a5e315bd79.png)

**Comment by vtamara** [comment]
O1.I1
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-43-03 p- m-](https://user-images.githubusercontent.com/701221/125138721-c784f480-e0d4-11eb-9283-d4e5d24484dc.png)

O1.I2
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-43-39 p- m-](https://user-images.githubusercontent.com/701221/125138750-d66ba700-e0d4-11eb-9fc4-b743fef5b21f.png)


O2.I1
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-44-08 p- m-](https://user-images.githubusercontent.com/701221/125138784-e5eaf000-e0d4-11eb-8a8c-68503320fdf2.png)

O2.I2
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-45-48 p- m-](https://user-images.githubusercontent.com/701221/125138911-2185ba00-e0d5-11eb-9b07-b8eb53b8c7ff.png)

O3.I1
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-46-09 p- m-](https://user-images.githubusercontent.com/701221/125138936-2ea2a900-e0d5-11eb-8ca7-d6af08907de1.png)

O3.I2
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-48-25 p- m-](https://user-images.githubusercontent.com/701221/125139082-7de8d980-e0d5-11eb-9f29-a89c2a76920a.png)

**Comment by vtamara** [comment]
![Crecer CINEP-PPP 1-0-b5 9-7-2021 4-50-04 p- m-](https://user-images.githubusercontent.com/701221/125139216-c2747500-e0d5-11eb-8a46-7fad432a6d3d.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-14 14-56-52](https://user-images.githubusercontent.com/10052756/125684806-3d504fe9-cfa9-44b9-bc3e-33ef0ad48e1c.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 16-50-24](https://user-images.githubusercontent.com/10052756/126231975-51b7c78d-a480-48d1-bd22-ff7d97815d0a.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-44-06](https://user-images.githubusercontent.com/10052756/126236857-c05f2c8d-67fd-45f0-8bbf-e459a68b49a7.png)

**Comment by BlancaInesAcosta** [comment]
P-U-91  Probar  R-91, R-98, R-97, R-96, F-81, F-80  [1]
