### ISSUE TITLE
R-96 En formulario actividad, al elegir un actividad de marco lógico que sea de publicación (objetivos 4 a 6) que permita especificar a que producto planeado corresponde (o ninguno) [1]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#96]

**Comment by vtamara** [comment]
Por ejemplo si no se han elegido actividades de marco lógico, el campo planeación de publicación no tiene opciones:
![Crecer CINEP-PPP 1-0-b5 15-7-2021 9-30-17 a- m-](https://user-images.githubusercontent.com/701221/125805404-90127828-036b-4b16-b60a-c944d38b390f.png)

![Crecer CINEP-PPP 1-0-b5 15-7-2021 9-30-43 a- m-](https://user-images.githubusercontent.com/701221/125805496-9ee11fbd-5cb1-4721-984a-6b5e39040097.png)

**Comment by vtamara** [comment]
Pero al elegir una actividad de marco lógico de entre los objetivos 4 a 6, permite elegir entre los respectivos productos planeados que no se hubieran usado en otra actividad.

Por ejemplo si publicación del número 1 en el trienio de la revista Noche y Niebla no se ha usado en otra actividad, estará disponible entre las elegibles:
![Crecer CINEP-PPP 1-0-b5 15-7-2021 9-32-39 a- m-](https://user-images.githubusercontent.com/701221/125805796-41a6a1a0-efe6-4314-b73e-d4e90d1e40a4.png)

![opcionesnyn1](https://user-images.githubusercontent.com/701221/125805941-4e081d6e-900d-4c4e-ac9d-a62562afb280.png)

Si en una actividad se elije esa:
![Crecer CINEP-PPP 1-0-b5 15-7-2021 9-34-06 a- m-](https://user-images.githubusercontent.com/701221/125806045-c0f5ddd3-32d2-4dd9-ad8b-22c22970722a.png)

Ya no estará disponible en otras actividades que tengan la actividad de marco lógico de publicación de Noche y Niebla:

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-03-38](https://user-images.githubusercontent.com/10052756/126233376-ef42c564-f8cc-49f8-b528-aa5e5c8ef101.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-09-15](https://user-images.githubusercontent.com/10052756/126233889-9dafd8ea-3f34-4d06-b398-4c261f7ff876.png)
![Captura de pantalla de 2021-07-19 17-10-07](https://user-images.githubusercontent.com/10052756/126233890-c3a25de4-2508-4cf3-b72b-925508236dcc.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-55-59](https://user-images.githubusercontent.com/10052756/126237847-48700b15-23b8-4a6e-b19c-acfa3b1c3a6d.png)
