### ISSUE TITLE
R-97 En formulario de compromiso institucional, en producto cambiar indicador al que hace referencia por actividad de marco lógico relacionada [1]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#97]

**Comment by vtamara** [comment]
![Crecer CINEP-PPP 1-0-b5 15-7-2021 9-25-39 a- m-](https://user-images.githubusercontent.com/701221/125804689-a3925bb3-c209-40a7-aa04-28b797a7152f.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 17-49-30](https://user-images.githubusercontent.com/10052756/126237321-9e64f920-fc2c-43dd-83d0-aff02563bfe4.png)
