### ISSUE TITLE
R-98 Incluir planeación de todos los productos mencionados en los indicadores de Objetivos 4 a 6 [3]

### ISSUE THREAD

**Issue by vtamara** [pasosdeJesus/cor1440_cinep#98]

**Comment by vtamara** [comment]
Desde el resumen del plan trienal ya se ven los 96 productos planeados:

![screencapture-crecer-cinep-org-co-4000-proyectosfinancieros-21-2021-07-15-09_16_45](https://user-images.githubusercontent.com/701221/125803710-362bb869-fcfe-4729-a931-a527868a3ca8.png)

**Comment by BlancaInesAcosta** [comment]
![Captura de pantalla de 2021-07-19 16-58-01](https://user-images.githubusercontent.com/10052756/126232775-3fd73427-8b4c-4334-b3c2-eedd4d8a5c19.png)
